<?xml version="1.0" encoding="UTF-8"?>
<definitions name="shippingService"
  targetNamespace="http://example.org/auth"
  xmlns:tns="http://example.org/auth"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns="http://schemas.xmlsoap.org/wsdl/">

  <message name="shippingCostRequest">
    <part name="Shipping_cost" type="xsd:integer"/>
  </message>

  <message name="shippingCostResponse">
    <part name="result" />
  </message>

  <portType name="shippingCostPortType">
    <operation name="shippingCost">
      <input message="tns:shippingCostRequest"/>
      <output message="tns:shippingCostResponse"/>
    </operation>
  </portType>

  <binding name="shippingCostBinding" type="tns:shippingCostPortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="shippingCost">
      <soap:operation soapAction="urn:xmethods-delayed-quotes#auth"/>
      <input>
        <soap:body use="encoded" namespace="urn:xmethods-delayed-quotes" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output>
        <soap:body use="encoded" namespace="urn:xmethods-delayed-quotes" encodingStyle="http://schemas.xmlsoap.org/soap/encoding"/>
      </output>
    </operation>
  </binding>

  <service name="shippingService">
    <port name="shippingCostPort" binding="tns:shippingCostBinding">
      <soap:address location="http://localhost:3000/shipping"/>
    </port>
  </service>

</definitions>
