<?xml version="1.0" encoding="UTF-8"?>
<definitions name="Shipping"
  targetNamespace="http://example.org/Shipping"
  xmlns:tns="http://example.org/Shipping"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns="http://schemas.xmlsoap.org/wsdl/">

  <!-- New Product -->
  <message name="shippingCostRequest">
    <part name="Shipping_cost" type="xsd:integer"/>
  </message>

  <message name="shippingCostResponse">
    <part name="result" />
  </message>

  <portType name="shippingPortType">
    <operation name="shippingCost">
      <input message="tns:shippingCostRequest"/>
      <output message="tns:shippingCostResponse"/>
    </operation>
  </portType>

  <!-- Shipping Cost -->
  <binding name="shippingBinding" type="tns:shippingPortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="shippingCost">
      <soap:operation soapAction="urn:xmethods-delayed-quotes#shippingCost"/>
      <input>
        <soap:body use="encoded" namespace="urn:xmethods-delayed-quotes" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output>
        <soap:body use="encoded" namespace="urn:xmethods-delayed-quotes" encodingStyle="http://schemas.xmlsoap.org/soap/encoding"/>
      </output>
    </operation>
  </binding>

  <!-- Service Set Up -->
  <service name="ShippingService">
    <port name="shippingPort" binding="tns:shippingBinding">
      <soap:address location="http://localhost:3000/ShippingService"/>
    </port>
  </service>
</definitions>
